<template>
  <q-page padding>
    <div class="text-h4 q-mb-md">
      Advanced Full-Stack Demo (Quasar + Express)
    </div>

    <!-- Git Workflow -->
    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6">Git Workflow</div>
        <q-list bordered separator class="q-mt-sm">
          <q-item v-for="(step, index) in gitSteps" :key="index">
            <q-item-section avatar>
              <q-badge>{{ index + 1 }}</q-badge>
            </q-item-section>
            <q-item-section>
              <q-item-label>{{ step.title }}</q-item-label>
              <q-item-label caption>{{ step.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <!-- Docker Concepts -->
    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6">Docker Concepts</div>
        <q-list bordered separator class="q-mt-sm">
          <q-item v-for="(item, index) in dockerItems" :key="index">
            <q-item-section>
              <q-item-label>{{ item.title }}</q-item-label>
              <q-item-label caption>{{ item.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>
  </q-page>
</template>

<script setup>
import { ref } from 'vue';

const gitSteps = [
  { title: 'Feature Branch', detail: 'Create a new branch for each feature' },
  { title: 'Commit', detail: 'Commit changes with clear messages' },
  { title: 'Push', detail: 'Push branch to remote repository' },
  { title: 'Pull Request', detail: 'Create PR for code review' },
  { title: 'Merge', detail: 'Merge PR into main branch' }
];

const dockerItems = [
  { title: 'Containerization', detail: 'Package application with dependencies' },
  { title: 'Images', detail: 'Read-only templates for containers' },
  { title: 'Compose', detail: 'Define and run multi-container applications' },
  { title: 'Volumes', detail: 'Persist data generated by and used by Docker containers' },
  { title: 'Networks', detail: 'Enable communication between containers' }
];
</script>
