<template>
  <q-page padding>
    <div class="text-h4 q-mb-md">
      Advanced Full-Stack Demo (Quasar + Express)
    </div>

    <!-- Git Workflow -->
    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6">Git Workflow</div>
        <q-list bordered separator class="q-mt-sm">
          <q-item v-for="(step, index) in gitSteps" :key="index">
            <q-item-section avatar>
              <q-badge>{{ index + 1 }}</q-badge>
            </q-item-section>
            <q-item-section>
              <q-item-label>{{ step.title }}</q-item-label>
              <q-item-label caption>{{ step.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <!-- Docker Concepts -->
    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6">Docker Concepts</div>
        <q-list bordered separator class="q-mt-sm">
          <q-item v-for="(item, index) in dockerItems" :key="index">
            <q-item-section>
              <q-item-label>{{ item.title }}</q-item-label>
              <q-item-label caption>{{ item.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <!-- New: API Data from Backend -->
    <q-card>
      <q-card-section>
        <div class="text-h6">Data from Backend API</div>
        <q-spinner v-if="loading" color="primary" size="2em" />
        <div v-else-if="error" class="text-negative">{{ error }}</div>
        <q-list v-else bordered separator class="q-mt-sm">
          <q-item>
            <q-item-section>
              <q-item-label>Advanced Git</q-item-label>
              <q-item-label caption>{{ apiData.git?.detail }}</q-item-label>
            </q-item-section>
          </q-item>
          <q-item>
            <q-item-section>
              <q-item-label>Advanced Docker</q-item-label>
              <q-item-label caption>{{ apiData.docker?.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
        <q-btn v-if="!loading" color="primary" @click="fetchData" class="q-mt-sm">Refresh Data</q-btn>
      </q-card-section>
    </q-card>
  </q-page>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';

const gitSteps = [
  { title: 'Feature Branch', detail: 'Create a new branch for each feature' },
  { title: 'Commit', detail: 'Commit changes with clear messages' },
  { title: 'Push', detail: 'Push branch to remote repository' },
  { title: 'Pull Request', detail: 'Create PR for code review' },
  { title: 'Merge', detail: 'Merge PR into main branch' }
];

const dockerItems = [
  { title: 'Containerization', detail: 'Package application with dependencies' },
  { title: 'Images', detail: 'Read-only templates for containers' },
  { title: 'Compose', detail: 'Define and run multi-container applications' },
  { title: 'Volumes', detail: 'Persist data generated by and used by Docker containers' },
  { title: 'Networks', detail: 'Enable communication between containers' }
];

const apiData = ref({ git: {}, docker: {} });
const loading = ref(true);
const error = ref(null);

const fetchData = async () => {
  loading.value = true;
  error.value = null;
  try {
    // In Docker, often better to use relative if proxy is set, or specific env var
    // Defaulting to localhost:3000 for browser-based access if env not set
    const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000';
    const response = await axios.get(`${apiUrl}/api/demo`);
    apiData.value = response.data;
  } catch (err) {
    console.error('API Error:', err);
    error.value = 'Failed to fetch data from backend';
  } finally {
    loading.value = false;
  }
};

onMounted(fetchData);
</script>
